version: "3.6"
services:
  restaurant-with-rails:
    image: restaurant-with-rails
    build:
      context: .
    container_name: restaurant-with-rails
    hostname: restaurant-with-rails
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    volumes:
      - .:/restaurant-with-rails:delegated
      - /restaurant-with-rails/node_modules
      - gems:/home/restaurant-with-rails:delegated
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - gems
    networks:
      - default

  gems:
    image: busybox:latest
    volumes:
      - /gems

  postgres:
    image: postgres:9.6.6-alpine
    container_name: restaurant-with-rails-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pg-data:/var/lib/postgresql:delegated
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
    name: restaurant-with-rails

volumes:
  gems:
  pg-data:
  node_modules: